### ISSUE TITLE
Your component is featured on my blog

### ISSUE THREAD

**Issue by binbalenci** [Juravenator/progress-spinner#1]
Hey @Juravenator,  

I just wrote a blog to talk about the best free spinner web components and I think, personally, yours is really cool. It kind of resembles the Chrome one and I really love the ease-in-out animation (not sure if I use the correct term) you have there.  
  
Here's the link to the blog [Top 5 spinners](https://vaadin.com/blog/5-spinner-web-components-for-your-site).  
  
It would be really cool if you give it some feedbacks/thoughts in the comment section.  
  
Regards,  
Binh

**Comment by Juravenator** [comment]
Thank you for the kind words @binhbbui411, I really appreciate it :)

If you have encountered compatibility issues (for example, I notice an absence of IE and iPhone X compatibility), please let me know and I can see if these can be fixed.

Cheers
Jura

**Comment by binbalenci** [comment]
It works on iPhone X, you can see the mobile-friend box is ticked ;) However, for IE, as I have not tried to bundle the component to test so it's a little bit misleading.

Anyhow, you have an awesome component man. Glad that you like the blog!

Regards,
Binh
